### ISSUE TITLE
Add vue-router as a default router system.

### ISSUE THREAD

**Issue by YobertyAlej** [leMaur/phonegap-vueify#3]
Hi, this has been really useful to me and i want to say thank you for that.

In any case, it would be good to have a router system already defined because the most of the times we use it in our projects.

Btw i would love to contribute with this project if you wish.

**Comment by leMaur** [comment]
Hi @YobertyAlej,
I am happy if this helps you.

To answer your question, I prefer leave this choice out of the project because every developer can use his router system. For example I prefer use Vuex instead of vue-router because I have found it a little bit faster.

Anyway feel free to fork it and create your preferred version.
If you want to know more about Vuex and how does it work can you check this project: https://drive.google.com/open?id=0B4iSz2fbmT7EYjl5THdGYkJQWUU


Happy coding,
Maurizio
